### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by btcbobbington** [ln-markets/trading-bot#7]
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    bot = launcher.bot()
  File "launcher.py", line 20, in bot
    return TAS.ta_summary(TAS(lnm_options), 
  File "strategies/ta_summary.py", line 15, in __init__
    self.lnm = lnm_client(self.options)
  File "lnm_client.py", line 14, in __init__
    if len(json.loads(self.lnm.get_user())['uid']) != 36:
KeyError: 'uid'

**Comment by romainlnm** [comment]
Hey,

Have you entered your API credentials in configuration.yml?

Then it should work properly, it does for me!

Cheers,
Romain

**Comment by btcbobbington** [comment]
Hey thanks for the quick reply. The APi has all the boxes checked and they are entered correctly in the code.

**Comment by RomainRouphael** [comment]
You're welcome!

Can you try with this in credentials.yml?
`## your personal information from LNMarkets
lnm_credentials: 
  key: 'EEwIHlF0KpQ/1+QlPb9tq484XALlyMP5alOyv1AsOas='
  secret: '46au19Ww3K/IU7+SmXHOZaCJP9WiQ8xP67HhQPV71SQ7IZQ6oPzOzJEkQ2/Cj6VNmXtZSYGWc6rt4jrarrlPWg=='
  passphrase: '3i285eh6fac9'
  network: 'testnet'

## choose your strategy while affecting True (and False to other strategies)
strategies:
  #Trading strat based on TA Summary: https://www.tradingview.com/symbols/XBTUSD/technicals/
  ta_summary: True
  

## parameters for strategies
ta_summary:
  quantity: 10 #type=int, min=1, quantity of each open position
  leverage: 10 #type=int, min=1, max=100
  takeprofit: 0.02 #type=float, price to reach above (for long) or below (for short) entry price to take profit, 0.2 means take profit 20% above or below entry price 
  stoploss: 0.02 #type=float, price to reach below (for long) or above (for short) entry price to stop loss, 0.1 means stop loss 10% below or above entry price
  interval: '1m' #type=string, available interval between 2 TA summary signals: "1m" for 1 minute, "5m" for 5 minutes, "15m" for 15 minutes, "30m" for 30 minutes, "1h" for 1 hour, "2h" for 2 hours, "4h" for 4 hours, "1d" for 1 day, "1W" for 1 week, "1M" for 1 month
  timeout: 60 #type=int, min=1, number of minutes the trading strat will be running2
`

**Comment by btcbobbington** [comment]
Ah.. wait. I pasted the wrong error. Thats from earlier. Running again to get the correct error. One moment.

**Comment by btcbobbington** [comment]
This is the correct error: 
```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    bot = launcher.bot()
  File "launcher.py", line 20, in bot
    return TAS.ta_summary(TAS(lnm_options), 
  File "strategies/ta_summary.py", line 144, in ta_summary
    id = json.loads(self.lnm.market_short(quantity = quantity, leverage = leverage, takeprofit = tp, stoploss = sl))['id']
KeyError: 'id'
```

**Comment by romainlnm** [comment]
Oh i think it's because you're running LNM module with API V1.
This code is with API V2, where id replaces uid for trades..

Can you upgrade to the latest version of LNM Python Module running pip install ln-markets==2.0.1?
https://pypi.org/project/ln-markets/

Then it should work fine

**Comment by btcbobbington** [comment]
I get the following: 

> Requirement already satisfied: ln-markets==2.0.1

**Comment by romainlnm** [comment]
Thanks, are you sure that's the module running in the trading bot environment?
When you have different python versions on the same computer it can be a bit tricky..
Sometimes the latest version of LNM package is installed in one Python environment, not in the other.

Meanwhile, running the bot to try to replicate the error!

**Comment by btcbobbington** [comment]
I'm completely new to anything code related. I downloaded the package as suggested. 
I rant the requirements code. 
then in my terminal I ran 
python3 main.py 

Then thats it. 

I appreciate your time btw, thank you.

**Comment by romainlnm** [comment]
Ok, seems correct!

Launching it to try to replicate.

Appreciate your time in notifying these errors thanks!

**Comment by romainlnm** [comment]
Can you try to run this and see if it works please?

options = {'key': 'EEwIHlF0KpQ/1+QlPb9tq484XALlyMP5alOyv1AsOas=', 
           'secret': '46au19Ww3K/IU7+SmXHOZaCJP9WiQ8xP67HhQPV71SQ7IZQ6oPzOzJEkQ2/Cj6VNmXtZSYGWc6rt4jrarrlPWg==', 
           'passphrase': '3i285eh6fac9',
           'network': 'testnet'}

lnm = rest.LNMarketsRest(**options)

print(lnm.futures_get_ticker())

print(lnm.futures_get_positions({'type':'closed'}))

**Comment by btcbobbington** [comment]
> Can you try to run this and see if it works please?
> 
> options = {'key': 'EEwIHlF0KpQ/1+QlPb9tq484XALlyMP5alOyv1AsOas=', 'secret': '46au19Ww3K/IU7+SmXHOZaCJP9WiQ8xP67HhQPV71SQ7IZQ6oPzOzJEkQ2/Cj6VNmXtZSYGWc6rt4jrarrlPWg==', 'passphrase': '3i285eh6fac9', 'network': 'testnet'}
> 
> lnm = rest.LNMarketsRest(**options)
> 
> print(lnm.futures_get_ticker())
> 
> print(lnm.futures_get_positions({'type':'closed'}))

In what file?

**Comment by romainlnm** [comment]
in a new python file you can call test_api.py, that you can run in a terminal

**Comment by btcbobbington** [comment]
> options = {'key': 'EEwIHlF0KpQ/1+QlPb9tq484XALlyMP5alOyv1AsOas=', 'secret': '46au19Ww3K/IU7+SmXHOZaCJP9WiQ8xP67HhQPV71SQ7IZQ6oPzOzJEkQ2/Cj6VNmXtZSYGWc6rt4jrarrlPWg==', 'passphrase': '3i285eh6fac9', 'network': 'testnet'}
> 
> lnm = rest.LNMarketsRest(**options)
> 
> print(lnm.futures_get_ticker())
> 
> print(lnm.futures_get_positions({'type':'closed'}))

lnm = rest.LNMarketsRest(**options)
NameError: name 'rest' is not defined

**Comment by romainlnm** [comment]
sorry my bad, with this as first line

from lnmarkets import rest

**Comment by btcbobbington** [comment]
{"lastPrice":28823,"index":28835.45,"carryIndicativeFeeRate":0.0001,"carryFeeTimestamp":1687348800000}
[{"market_filled_ts":1687336767231,"creation_ts":1687336767231,"closed_ts":1687337014764,"id":"0d0d43b9-d74f-4126-8e2e-c714d7bab860","uid":"e70e0b85-4fed-4b4f-bff4-dbe52cf57759","side":"s","type":"m","quantity":1,"price":28812.5,"margin":347,"liquidation":32013,"stoploss":29389,"takeprofit":28236,"pl":0,"open":false,"running":false,"canceled":false,"closed":true,"exit_price":28809,"leverage":10,"maintenance_margin":0,"opening_fee":3,"closing_fee":3,"sum_carry_fees":0},{"market_filled_ts":1687248974783,"creation_ts":1687248974783,"closed_ts":1687248979798,"id":"3d575b75-78c1-4569-9b1c-4823d56d1d70","uid":"e70e0b85-4fed-4b4f-bff4-dbe52cf57759","side":"b","type":"m","quantity":100,"price":26766,"margin":37360,"liquidation":24333,"pl":0,"open":false,"running":false,"canceled":false,"closed":true,"exit_price":26766,"leverage":10,"maintenance_margin":37,"opening_fee":373,"closing_fee":373,"sum_carry_fees":0}]

**Comment by romainlnm** [comment]
Ok so you are indeed running the latest api version!

Did not manage to replicate your error yet, will dig in!

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    bot = launcher.bot()
  File "launcher.py", line 20, in bot
    return TAS.ta_summary(TAS(lnm_options), 
  File "strategies/ta_summary.py", line 144, in ta_summary
    id = json.loads(self.lnm.market_short(quantity = quantity, leverage = leverage, takeprofit = tp, stoploss = sl))['id']
KeyError: 'id'

**Comment by btcbobbington** [comment]
Here is some more information if it helps. 

Recently (for some unknown reason) it seems to work a little better. 

I changed the following setting to 2 mins: 

```
  timeout: 2 #type=int, min=1, number of minutes the trading strat will be running2

```

When I run the code I get the following: 

```
INFO:root:Connection to LN Markets ok!
{'RECOMMENDATION': 'BUY', 'BUY': 15, 'SELL': 3, 'NEUTRAL': 8}
{'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 2, 'NEUTRAL': 10}
{'RECOMMENDATION': 'STRONG_BUY', 'BUY': 15, 'SELL': 1, 'NEUTRAL': 10}
```

Then after the 2 mins has finished, I get the following: 

```
INFO:root:2023-06-21 21:19:12.338410

INFO:root:New Market Buy Running for Quantity = 10, leverage = 10, take profit = 29575, stop loss = 28415

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    bot = launcher.bot()
  File "launcher.py", line 20, in bot
    return TAS.ta_summary(TAS(lnm_options), 
  File "strategies/ta_summary.py", line 137, in ta_summary
    id = json.loads(self.lnm.market_long(quantity = quantity, leverage = leverage, takeprofit = tp, stoploss = sl))['id']
KeyError: 'id'
```

Also, when I check lnmarkets website - I do not see any change. No trades are placed and my value doesnt go down. I currently have `1,000` sats in there for test purposes. 

Also 2: When I am on the lnmarkets website (I know this probably has nothing to do with you) - but when I try to manually press all in. I get the following error:

> request/body/margin must be >= 1 

So perhaps some of the issues are coming from the website? 


I'm sorry I am not skilled enough to help you further.

**Comment by romainlnm** [comment]
Hey,

Thanks for sharing!

From what i'm seeing, the trading strat was supposed to run for 2 minutes only.
It seems that during that time, since it had a strong buy signal, it went long, as shown here:
INFO:root:New Market Buy Running for Quantity = 10, leverage = 10, take profit = 29575, stop loss = 28415

When the bot stopped, i guess the long was still open.

Have you tried to refresh the page?
You should see it!

Also, the all in error means your balance is null.

What i suggest is try it out on testnet.lnmarkets.com -> you have 200,000 sats testnet free for testing, you can generate your testnet api keys and try the bot (in credentials.ylm you must add 'network':'testnet' in options.

This will make it easier to try everything out.

Thanks for trying our stuff!!

**Comment by btcbobbington** [comment]
Hey Good Morning/Evening

I have tested the bot this morning with testnet.. Here are the results: 

Output: 
```
{'RECOMMENDATION': 'SELL', 'BUY': 2, 'SELL': 15, 'NEUTRAL': 9}
{'RECOMMENDATION': 'STRONG_SELL', 'BUY': 0, 'SELL': 16, 'NEUTRAL': 10}
INFO:root:2023-06-22 09:04:24.330044
INFO:root:New Market Sell Running for Quantity = 10, leverage = 10, take profit = 29397, stop loss = 30596
```

When I check the testnet website there is indeed a running position. 

I think there might be some confusion (on my part) as to what happens. I assumed that for every console log: 
```
{'RECOMMENDATION': 'SELL', 'BUY': 2, 'SELL': 15, 'NEUTRAL': 9}
{'RECOMMENDATION': 'STRONG_SELL', 'BUY': 0, 'SELL': 16, 'NEUTRAL': 10}
```

Something would happen on the lightning website. Is this not the case? 

I have changed the time frame and am running it for 30 mins now. I will update my findings/any errors.

**Comment by btcbobbington** [comment]
ok. It ran for longer. The results were: 

```
{'RECOMMENDATION': 'BUY', 'BUY': 11, 'SELL': 6, 'NEUTRAL': 9}
{'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 4, 'NEUTRAL': 8}
{'RECOMMENDATION': 'BUY', 'BUY': 13, 'SELL': 5, 'NEUTRAL': 8}
{'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 4, 'NEUTRAL': 8}
{'RECOMMENDATION': 'BUY', 'BUY': 12, 'SELL': 7, 'NEUTRAL': 7}
{'RECOMMENDATION': 'BUY', 'BUY': 12, 'SELL': 8, 'NEUTRAL': 6}
{'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 3, 'NEUTRAL': 9}
{'RECOMMENDATION': 'BUY', 'BUY': 15, 'SELL': 3, 'NEUTRAL': 8}
{'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 4, 'NEUTRAL': 8}
{'RECOMMENDATION': 'BUY', 'BUY': 13, 'SELL': 6, 'NEUTRAL': 7}
{'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 4, 'NEUTRAL': 8}
{'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 4, 'NEUTRAL': 8}
{'RECOMMENDATION': 'BUY', 'BUY': 13, 'SELL': 4, 'NEUTRAL': 9}
{'RECOMMENDATION': 'BUY', 'BUY': 15, 'SELL': 3, 'NEUTRAL': 8}
{'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 3, 'NEUTRAL': 9}
{'RECOMMENDATION': 'STRONG_BUY', 'BUY': 17, 'SELL': 1, 'NEUTRAL': 8}
INFO:root:2023-06-22 09:40:35.056728
INFO:root:New Market Buy Running for Quantity = 10, leverage = 10, take profit = 30809, stop loss = 29600
{'RECOMMENDATION': 'BUY', 'BUY': 15, 'SELL': 3, 'NEUTRAL': 8}
INFO:root:Keep long open
{'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 2, 'NEUTRAL': 10}
INFO:root:Keep long open
{'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 3, 'NEUTRAL': 9}
INFO:root:Keep long open
{'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 2, 'NEUTRAL': 10}
INFO:root:Keep long open
{'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 2, 'NEUTRAL': 10}
INFO:root:Keep long open
{'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 2, 'NEUTRAL': 10}
INFO:root:Keep long open
{'RECOMMENDATION': 'NEUTRAL', 'BUY': 11, 'SELL': 5, 'NEUTRAL': 10}
INFO:root:2023-06-22 09:47:55.074918
INFO:root:Close position id = 53765a46-37dd-42a2-abbe-c891afce2873
```

That included a 7 sat profit.. However there was a trading fee of 66sats. So still a loss. 
In terms of the bot, it seems to work correctly and even generated the file. 

After the two positions ran, my remaining balance from the free 200k sats was: **196,548**.
There were two trades in total. 

1) -7 Loss
2) +7 Profit. 

Both had 66sat trading fee so total of: 132. 

> 200,000 - 132 = 199868

Not sure why I only have **196,548** left. Does the bot take a fee? 


I will test again on mainnet and let you know.

**Comment by btcbobbington** [comment]
ok, I ran it on **mainnet** and got the following error:

```
'RECOMMENDATION': 'NEUTRAL', 'BUY': 6, 'SELL': 10, 'NEUTRAL': 10}
{'RECOMMENDATION': 'SELL', 'BUY': 6, 'SELL': 13, 'NEUTRAL': 7}
{'RECOMMENDATION': 'BUY', 'BUY': 12, 'SELL': 4, 'NEUTRAL': 10}
{'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 2, 'NEUTRAL': 10}
{'RECOMMENDATION': 'BUY', 'BUY': 13, 'SELL': 3, 'NEUTRAL': 10}
{'RECOMMENDATION': 'BUY', 'BUY': 13, 'SELL': 4, 'NEUTRAL': 9}
{'RECOMMENDATION': 'STRONG_BUY', 'BUY': 15, 'SELL': 1, 'NEUTRAL': 10}
INFO:root:2023-06-22 10:43:58.291188
INFO:root:New Market Buy Running for Quantity = 10, leverage = 10, take profit = 30768, stop loss = 29561
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    bot = launcher.bot()
  File "launcher.py", line 20, in bot
    return TAS.ta_summary(TAS(lnm_options), 
  File "strategies/ta_summary.py", line 137, in ta_summary
    id = json.loads(self.lnm.market_long(quantity = quantity, leverage = leverage, takeprofit = tp, stoploss = sl))['id']
KeyError: 'id'
```

**Comment by romainlnm** [comment]
> Hey Good Morning/Evening
> 
> I have tested the bot this morning with testnet.. Here are the results:
> 
> Output:
> 
> ```
> {'RECOMMENDATION': 'SELL', 'BUY': 2, 'SELL': 15, 'NEUTRAL': 9}
> {'RECOMMENDATION': 'STRONG_SELL', 'BUY': 0, 'SELL': 16, 'NEUTRAL': 10}
> INFO:root:2023-06-22 09:04:24.330044
> INFO:root:New Market Sell Running for Quantity = 10, leverage = 10, take profit = 29397, stop loss = 30596
> ```
> 
> When I check the testnet website there is indeed a running position.
> 
> I think there might be some confusion (on my part) as to what happens. I assumed that for every console log:
> 
> ```
> {'RECOMMENDATION': 'SELL', 'BUY': 2, 'SELL': 15, 'NEUTRAL': 9}
> {'RECOMMENDATION': 'STRONG_SELL', 'BUY': 0, 'SELL': 16, 'NEUTRAL': 10}
> ```
> 
> Something would happen on the lightning website. Is this not the case?
> 
> I have changed the time frame and am running it for 30 mins now. I will update my findings/any errors.

Hey, 

No in the current bot implementation, it only opens a long position when there is a Strong Buy recommendation and a short position when there is a Strong Sell recommendation. Positions are closed whenever this strong signal ceases to exist or when a take profit, stop loss or liquidation event occurs.

**Comment by romainlnm** [comment]
> ok. It ran for longer. The results were:
> 
> ```
> {'RECOMMENDATION': 'BUY', 'BUY': 11, 'SELL': 6, 'NEUTRAL': 9}
> {'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 4, 'NEUTRAL': 8}
> {'RECOMMENDATION': 'BUY', 'BUY': 13, 'SELL': 5, 'NEUTRAL': 8}
> {'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 4, 'NEUTRAL': 8}
> {'RECOMMENDATION': 'BUY', 'BUY': 12, 'SELL': 7, 'NEUTRAL': 7}
> {'RECOMMENDATION': 'BUY', 'BUY': 12, 'SELL': 8, 'NEUTRAL': 6}
> {'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 3, 'NEUTRAL': 9}
> {'RECOMMENDATION': 'BUY', 'BUY': 15, 'SELL': 3, 'NEUTRAL': 8}
> {'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 4, 'NEUTRAL': 8}
> {'RECOMMENDATION': 'BUY', 'BUY': 13, 'SELL': 6, 'NEUTRAL': 7}
> {'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 4, 'NEUTRAL': 8}
> {'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 4, 'NEUTRAL': 8}
> {'RECOMMENDATION': 'BUY', 'BUY': 13, 'SELL': 4, 'NEUTRAL': 9}
> {'RECOMMENDATION': 'BUY', 'BUY': 15, 'SELL': 3, 'NEUTRAL': 8}
> {'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 3, 'NEUTRAL': 9}
> {'RECOMMENDATION': 'STRONG_BUY', 'BUY': 17, 'SELL': 1, 'NEUTRAL': 8}
> INFO:root:2023-06-22 09:40:35.056728
> INFO:root:New Market Buy Running for Quantity = 10, leverage = 10, take profit = 30809, stop loss = 29600
> {'RECOMMENDATION': 'BUY', 'BUY': 15, 'SELL': 3, 'NEUTRAL': 8}
> INFO:root:Keep long open
> {'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 2, 'NEUTRAL': 10}
> INFO:root:Keep long open
> {'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 3, 'NEUTRAL': 9}
> INFO:root:Keep long open
> {'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 2, 'NEUTRAL': 10}
> INFO:root:Keep long open
> {'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 2, 'NEUTRAL': 10}
> INFO:root:Keep long open
> {'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 2, 'NEUTRAL': 10}
> INFO:root:Keep long open
> {'RECOMMENDATION': 'NEUTRAL', 'BUY': 11, 'SELL': 5, 'NEUTRAL': 10}
> INFO:root:2023-06-22 09:47:55.074918
> INFO:root:Close position id = 53765a46-37dd-42a2-abbe-c891afce2873
> ```
> 
> That included a 7 sat profit.. However there was a trading fee of 66sats. So still a loss. In terms of the bot, it seems to work correctly and even generated the file.
> 
> After the two positions ran, my remaining balance from the free 200k sats was: **196,548**. There were two trades in total.
> 
>     1. -7 Loss
> 
>     2. +7 Profit.
> 
> 
> Both had 66sat trading fee so total of: 132.
> 
> > 200,000 - 132 = 199868
> 
> Not sure why I only have **196,548** left. Does the bot take a fee?
> 
> I will test again on mainnet and let you know.

No, the bot does not take any fee. Can you do in LNM settings / clear cache and check again? 
There are not other fees besides trading fees and carry fees (for positions opened for more than 8 hours, which is not the case here)

**Comment by romainlnm** [comment]
> ok, I ran it on **mainnet** and got the following error:
> 
> ```
> 'RECOMMENDATION': 'NEUTRAL', 'BUY': 6, 'SELL': 10, 'NEUTRAL': 10}
> {'RECOMMENDATION': 'SELL', 'BUY': 6, 'SELL': 13, 'NEUTRAL': 7}
> {'RECOMMENDATION': 'BUY', 'BUY': 12, 'SELL': 4, 'NEUTRAL': 10}
> {'RECOMMENDATION': 'BUY', 'BUY': 14, 'SELL': 2, 'NEUTRAL': 10}
> {'RECOMMENDATION': 'BUY', 'BUY': 13, 'SELL': 3, 'NEUTRAL': 10}
> {'RECOMMENDATION': 'BUY', 'BUY': 13, 'SELL': 4, 'NEUTRAL': 9}
> {'RECOMMENDATION': 'STRONG_BUY', 'BUY': 15, 'SELL': 1, 'NEUTRAL': 10}
> INFO:root:2023-06-22 10:43:58.291188
> INFO:root:New Market Buy Running for Quantity = 10, leverage = 10, take profit = 30768, stop loss = 29561
> Traceback (most recent call last):
>   File "main.py", line 7, in <module>
>     bot = launcher.bot()
>   File "launcher.py", line 20, in bot
>     return TAS.ta_summary(TAS(lnm_options), 
>   File "strategies/ta_summary.py", line 137, in ta_summary
>     id = json.loads(self.lnm.market_long(quantity = quantity, leverage = leverage, takeprofit = tp, stoploss = sl))['id']
> KeyError: 'id'
> ```

Thx i don't manage to replicate the error yet, will try again!

**Comment by makrron** [comment]
Hello, I have launched the bot as it comes in the Readme, I am receiving this error. I have searched the internet in case someone has the same error and I have not found anything.

```python
Traceback (most recent call last):
  File "trading-bot/main.py", line 7, in <module>
    bot = launcher.bot()
  File "trading-bot/launcher.py", line 22, in bot
    return TAS.ta_summary(TAS(lnm_options),
  File "trading-bot/strategies/ta_summary.py", line 80, in ta_summary
    num_pos_running = len(json.loads(self.lnm.get_positions(type_pos='running')))
  File "trading-bot/lnm_client.py", line 64, in get_positions
    return self.lnm.futures_get_positions(params)
AttributeError: 'LNMarketsRest' object has no attribute 'futures_get_positions'
```

I'm using 2.0.5 version of ln-markets library.

**Comment by romainlnm** [comment]
Hey sir,
Indeed, the function names of the python package have changed since I made this code, need to update them.
Thanks for the heads up!
Best,
Romain
